### PR TITLE
rename existing profiles models

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
@saeedmb8 @KaitCrawford @bruskiza review please 
Just want to make sure you're all familiar with data migrations.
In this particular case - we're introducing a new model and so we'd need to copy all the existing data from the old model to the new model before deleting it.

**Comment by bruskiza** [comment]
lgtm... can't comment on the code tho... seems simple enough.

We will never "undo" right?

**Comment by miltontony** [comment]
We can, reverse migrations still work - but in the case of the data migration - the "new model" will get deleted so there's no impact.

**Comment by smarzban** [comment]
:+1: :cake:

**Comment by KaitCrawford** [comment]
:+1:
for learning though, did you create those migrations files or did django automagically figure out that the new model would be replacing the old and create the migration to copy the data?

**Pull request merged**
