### PR TITLE
Please can we start the QA process for B-Wise. Let us know when it is deployed and we can start testing

### PR DESCRIPTION
**Pull request by smn**
Please let us know when we can start QA'ing the comments section for b-wise.

As discussed @smn

### CODE REVIEW

**Comment by smn** [comment]
End of today.

**Comment by smn** [comment]
this_is_a_first_level_article

**Comment by smn** [comment]
this_is_a_first_level_article

**Comment by smn** [comment]
@saeedmb8 & @bruskiza ready for review.

**Comment by smarzban** [comment]
👍🏻

**Comment by smn** [comment]
This also requires https://github.com/praekelt/molo.commenting/pull/5 to land.

**Pull request merged**
