### PR TITLE
Add molo.commenting

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by smn** [comment]
Not ready for review yet.

**Comment by smn** [comment]
commenting-bwise

@bruskiza progress update ^^^

**Comment by smn** [comment]
localhost_8000_commenting_molo_post_

Validation

**Comment by smn** [comment]
this_is_a_first_level_article

commenting results in a flash message showing that the comment has been reported, we still need styling for it though.

**Comment by smn** [comment]
@bruskiza & @saeedmb8 ready for review

**Comment by smarzban** [comment]
beautiful work @smn :cake: :100:  :+1:

**Comment by bruskiza** [comment]
concur... nice!

**Pull request merged**
