### PR TITLE
remove hardcoded link for poll results

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
@hodgestar review please

**Comment by hodgestar** [comment]
Code looks fine but tests are failing with:

```
File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/molo/profiles/models.py", line 6, in <module>
    from wagtail.contrib.settings.models import BaseSetting, register_setting
ImportError: No module named settings.models
```

**Comment by miltontony** [comment]
yeah, I'm looking into that

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
