### PR TITLE
Upload new logo

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by smn** [comment]
@bruskiza is this still relevant?

**Comment by bruskiza** [comment]
yes.. the new logo is TBA and still being confirmed. we will still need to upload the new logo once we have it.

**Comment by smn** [comment]
Eep! accidentally merged #25 here, apologies!

**Comment by smn** [comment]
Will re-open this shortly.

**Comment by smn** [comment]
ugh can't re-open after merging apparently. Sorry @bruskiza !

**Pull request closed without merging**
