### PR TITLE
Login page is missing styling

### PR DESCRIPTION
**Pull request by smn**
https://b-wise.mobi/login/

### CODE REVIEW

**Comment by smn** [comment]
screenshot_2015_08_12__12_32_pm

**Comment by smn** [comment]
screenshot_2015_08_12__12_32_pm

View my profile also missing styling.

**Comment by smn** [comment]
Change password too 
localhost_8000_password-reset__and_https___b-wise_mobi_login_

**Comment by smn** [comment]
Used http://praekelt.github.io/molo-ndoh-yep/profile.html as a template for the styling.
localhost_8000_edit_myprofile_

localhost_8000_view_myprofile_

localhost_8000_password-reset_

localhost_8000_login_

**Comment by smn** [comment]
Not perfect but closer. @saeedmb8 & @bruskiza ready for review.

**Comment by bruskiza** [comment]
:+1:

**Pull request merged**
