### PR TITLE
Indent second line of bullet points

### PR DESCRIPTION
**Pull request by KaitCrawford**

### CODE REVIEW

**Comment by KaitCrawford** [comment]
@peterp @Mitso ready for review. I have idea if I've made the changes in the correct place.

**Comment by peterp** [comment]
Can you provide a screenshot in the PR?

**Comment by KaitCrawford** [comment]
Previously:
bwise-not-indented-bullets

Now:
bwise-indented-bullets

**Comment by peterp** [comment]
👍

**Pull request merged**
